services:
  - type: web
    name: zoltar-edu
    env: python
    plan: free
    buildCommand: |
      # Instalar Rust (necesario para compilar tiktoken y dependencias de ChromaDB)
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source $HOME/.cargo/env

      # Instalar dependencias
      pip install --upgrade pip
      pip install -r requirements.txt

      # Construir embeddings al primer deploy
      python -m backend.ingest --rebuild
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false   # ⚠️ Configurar en Render Dashboard
      - key: EMBEDDINGS_PROVIDER
        value: openai
      - key: EMBEDDINGS_MODEL
        value: text-embedding-3-large
      - key: CHAT_MODEL
        value: gpt-4o-mini
      - key: CHAT_TEMPERATURE
        value: "0.2"
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data



