services:
  - type: web
    name: zoltar-edu
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m backend.ingest
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false   # ⚠️ Lo configuras en el panel de Render, no en GitHub
      - key: EMBEDDINGS_PROVIDER
        value: openai
      - key: EMBEDDINGS_MODEL
        value: text-embedding-3-large
      - key: CHAT_MODEL
        value: gpt-4o-mini
      - key: CHAT_TEMPERATURE
        value: "0.2"
